# Generated by Django 5.0.4 on 2024-06-03 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAccount', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carposts',
            old_name='user_id',
            new_name='user',
        ),
    ]
