# Generated by Django 5.0.4 on 2024-06-04 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAccount', '0004_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
