# Generated by Django 5.0.4 on 2024-06-03 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppKinda', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cars',
        ),
    ]
