# Generated by Django 5.0.4 on 2024-06-04 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppKinda', '0002_delete_cars'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
